### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [bsymon/romc#1]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project and not end up in proprietary derivatives.

**Comment by bsymon** [comment]
Hi ! Thank you to point that out 🙂 This is an old project, haven't looked at it for a while ... I've added a LICENSE has you suggested !

This is this one : https://unlicense.org/

I don't really have the time to handle this project anymore, people will do what they want with the code. If it happen that people want to contribute to this project, I may take the time to look for pull requests but I can't guarantee that ...
